import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { HydratedDocument, Types } from 'mongoose';

export type LectureStudyKitDocument = HydratedDocument<LectureStudyKit>;

// One question/answer pair for the flashcard deck.
@Schema({ _id: false })
export class Flashcard {
  @Prop({ required: true }) front: string;
  @Prop({ required: true }) back: string;
}
export const FlashcardSchema = SchemaFactory.createForClass(Flashcard);

// One multiple-choice practice question.
@Schema({ _id: false })
export class QuizItem {
  @Prop({ required: true }) question: string;
  @Prop({ type: [String], required: true }) options: string[];
  @Prop({ required: true }) answerIndex: number;
  @Prop({ default: '' }) explanation: string;
}
export const QuizItemSchema = SchemaFactory.createForClass(QuizItem);

// One term -> short definition entry.
@Schema({ _id: false })
export class GlossaryEntry {
  @Prop({ required: true }) term: string;
  @Prop({ required: true }) definition: string;
}
export const GlossaryEntrySchema = SchemaFactory.createForClass(GlossaryEntry);

// The AI-generated "study kit" for one lecture PDF (overview + key points + glossary +
// flashcards + practice quiz). Generated once, on demand, by the first student who opens the
// lecture's study tools, then cached and shared with everyone else who opens that same lecture.
// Regeneratable (findOneAndUpdate upsert on `post`). Keyed by the lecture's Post id.
@Schema({ timestamps: true })
export class LectureStudyKit {
  @Prop({ type: Types.ObjectId, ref: 'Post', required: true, unique: true, index: true })
  post: Types.ObjectId;

  @Prop({ type: String, default: null, index: true })
  courseCode: string | null;

  @Prop({ required: true }) overview: string;

  @Prop({ type: [String], default: [] }) keyPoints: string[];

  @Prop({ type: [GlossaryEntrySchema], default: [] }) glossary: GlossaryEntry[];

  @Prop({ type: [FlashcardSchema], default: [] }) flashcards: Flashcard[];

  @Prop({ type: [QuizItemSchema], default: [] }) quiz: QuizItem[];

  // Provider model that produced this kit + who triggered the (re)generation -- for the
  // "generated by AI" disclosure and admin insight. `sourceChars` is how much lecture text was
  // fed in (capped), useful when a kit looks thin.
  @Prop({ required: true }) model: string;

  @Prop({ type: Types.ObjectId, ref: 'User', required: true }) generatedBy: Types.ObjectId;

  @Prop({ default: 0 }) sourceChars: number;
}

export const LectureStudyKitSchema = SchemaFactory.createForClass(LectureStudyKit);
