// GENERATED by the sticker build script -- edit the source list, not this file.
// Artwork: "3d" = Microsoft Fluent Emoji (MIT); "anim" = Google Noto Emoji Animation (CC BY 4.0).
// See public/stickers/LICENSES.txt.

export interface CatalogSticker {
  /** What a message carries: "sticker:<set>/<id>" -- resolved to /stickers/<set>/<id>.webp. */
  ref: string;
  /** Arabic name: shown as a tooltip and matched by search. */
  label: string;
}

export interface CatalogPack {
  id: string;
  name: string;
  kind: 'image';
  items: CatalogSticker[];
}

export const STICKER_CATALOG: CatalogPack[] = [
  {
    "id": "faces",
    "name": "وجوه",
    "kind": "image",
    "items": [
      {
        "ref": "sticker:3d/grinning-face",
        "label": "ابتسامة"
      },
      {
        "ref": "sticker:3d/grinning-face-with-big-eyes",
        "label": "سعيد"
      },
      {
        "ref": "sticker:3d/grinning-face-with-smiling-eyes",
        "label": "فرحان"
      },
      {
        "ref": "sticker:3d/beaming-face-with-smiling-eyes",
        "label": "مبسوط"
      },
      {
        "ref": "sticker:3d/grinning-squinting-face",
        "label": "ضحكة"
      },
      {
        "ref": "sticker:3d/grinning-face-with-sweat",
        "label": "إحراج"
      },
      {
        "ref": "sticker:3d/rolling-on-the-floor-laughing",
        "label": "ميت من الضحك"
      },
      {
        "ref": "sticker:3d/face-with-tears-of-joy",
        "label": "ضحك"
      },
      {
        "ref": "sticker:3d/slightly-smiling-face",
        "label": "ابتسامة خفيفة"
      },
      {
        "ref": "sticker:3d/upside-down-face",
        "label": "مقلوب"
      },
      {
        "ref": "sticker:3d/melting-face",
        "label": "ذائب"
      },
      {
        "ref": "sticker:3d/winking-face",
        "label": "غمزة"
      },
      {
        "ref": "sticker:3d/smiling-face-with-smiling-eyes",
        "label": "خجول"
      },
      {
        "ref": "sticker:3d/smiling-face-with-halo",
        "label": "ملاك"
      },
      {
        "ref": "sticker:3d/smiling-face-with-hearts",
        "label": "حب"
      },
      {
        "ref": "sticker:3d/smiling-face-with-heart-eyes",
        "label": "معجب"
      },
      {
        "ref": "sticker:3d/star-struck",
        "label": "منبهر"
      },
      {
        "ref": "sticker:3d/face-blowing-a-kiss",
        "label": "قبلة"
      },
      {
        "ref": "sticker:3d/smiling-face-with-tear",
        "label": "دمعة فرح"
      },
      {
        "ref": "sticker:3d/face-savoring-food",
        "label": "لذيذ"
      },
      {
        "ref": "sticker:3d/face-with-tongue",
        "label": "لسان"
      },
      {
        "ref": "sticker:3d/winking-face-with-tongue",
        "label": "مشاكس"
      },
      {
        "ref": "sticker:3d/zany-face",
        "label": "مجنون"
      },
      {
        "ref": "sticker:3d/money-mouth-face",
        "label": "فلوس"
      },
      {
        "ref": "sticker:3d/hugging-face",
        "label": "حضن"
      },
      {
        "ref": "sticker:3d/face-with-hand-over-mouth",
        "label": "أوبس"
      },
      {
        "ref": "sticker:3d/face-with-open-eyes-and-hand-over-mouth",
        "label": "صدمة"
      },
      {
        "ref": "sticker:3d/shushing-face",
        "label": "هس"
      },
      {
        "ref": "sticker:3d/thinking-face",
        "label": "تفكير"
      },
      {
        "ref": "sticker:3d/saluting-face",
        "label": "تحية"
      },
      {
        "ref": "sticker:3d/zipper-mouth-face",
        "label": "سكوت"
      },
      {
        "ref": "sticker:3d/face-with-raised-eyebrow",
        "label": "شك"
      },
      {
        "ref": "sticker:3d/neutral-face",
        "label": "محايد"
      },
      {
        "ref": "sticker:3d/expressionless-face",
        "label": "بدون تعبير"
      },
      {
        "ref": "sticker:3d/face-without-mouth",
        "label": "بلا كلام"
      },
      {
        "ref": "sticker:3d/dotted-line-face",
        "label": "مختفي"
      },
      {
        "ref": "sticker:3d/smirking-face",
        "label": "خبيث"
      },
      {
        "ref": "sticker:3d/unamused-face",
        "label": "غير مقتنع"
      },
      {
        "ref": "sticker:3d/face-with-rolling-eyes",
        "label": "زهقان"
      },
      {
        "ref": "sticker:3d/grimacing-face",
        "label": "متوتر"
      },
      {
        "ref": "sticker:3d/relieved-face",
        "label": "مرتاح"
      },
      {
        "ref": "sticker:3d/pensive-face",
        "label": "حزين"
      },
      {
        "ref": "sticker:3d/sleepy-face",
        "label": "نعسان"
      },
      {
        "ref": "sticker:3d/sleeping-face",
        "label": "نائم"
      },
      {
        "ref": "sticker:3d/face-with-medical-mask",
        "label": "كمامة"
      },
      {
        "ref": "sticker:3d/hot-face",
        "label": "حر"
      },
      {
        "ref": "sticker:3d/cold-face",
        "label": "برد"
      },
      {
        "ref": "sticker:3d/woozy-face",
        "label": "دايخ"
      },
      {
        "ref": "sticker:3d/exploding-head",
        "label": "انفجار دماغ"
      },
      {
        "ref": "sticker:3d/cowboy-hat-face",
        "label": "كاوبوي"
      },
      {
        "ref": "sticker:3d/partying-face",
        "label": "حفلة"
      },
      {
        "ref": "sticker:3d/disguised-face",
        "label": "متنكر"
      },
      {
        "ref": "sticker:3d/smiling-face-with-sunglasses",
        "label": "كول"
      },
      {
        "ref": "sticker:3d/nerd-face",
        "label": "دحيح"
      },
      {
        "ref": "sticker:3d/face-with-monocle",
        "label": "محقق"
      },
      {
        "ref": "sticker:3d/confused-face",
        "label": "محتار"
      },
      {
        "ref": "sticker:3d/worried-face",
        "label": "قلقان"
      },
      {
        "ref": "sticker:3d/slightly-frowning-face",
        "label": "متضايق"
      },
      {
        "ref": "sticker:3d/face-with-open-mouth",
        "label": "مندهش"
      },
      {
        "ref": "sticker:3d/astonished-face",
        "label": "مذهول"
      },
      {
        "ref": "sticker:3d/flushed-face",
        "label": "محرج"
      },
      {
        "ref": "sticker:3d/pleading-face",
        "label": "رجاء"
      },
      {
        "ref": "sticker:3d/face-holding-back-tears",
        "label": "كاتم دموعه"
      },
      {
        "ref": "sticker:3d/anxious-face-with-sweat",
        "label": "قلق"
      },
      {
        "ref": "sticker:3d/crying-face",
        "label": "بكاء"
      },
      {
        "ref": "sticker:3d/loudly-crying-face",
        "label": "منهار"
      },
      {
        "ref": "sticker:3d/face-screaming-in-fear",
        "label": "رعب"
      },
      {
        "ref": "sticker:3d/confounded-face",
        "label": "مرتبك"
      },
      {
        "ref": "sticker:3d/weary-face",
        "label": "تعبان"
      },
      {
        "ref": "sticker:3d/tired-face",
        "label": "مرهق"
      },
      {
        "ref": "sticker:3d/yawning-face",
        "label": "تثاؤب"
      },
      {
        "ref": "sticker:3d/face-with-steam-from-nose",
        "label": "معصّب"
      },
      {
        "ref": "sticker:3d/pouting-face",
        "label": "غاضب"
      },
      {
        "ref": "sticker:3d/angry-face",
        "label": "زعلان"
      },
      {
        "ref": "sticker:3d/face-with-symbols-on-mouth",
        "label": "شتيمة"
      },
      {
        "ref": "sticker:3d/smiling-face-with-horns",
        "label": "شقي"
      },
      {
        "ref": "sticker:3d/skull",
        "label": "مت"
      },
      {
        "ref": "sticker:3d/clown-face",
        "label": "مهرج"
      },
      {
        "ref": "sticker:3d/ghost",
        "label": "شبح"
      },
      {
        "ref": "sticker:3d/alien",
        "label": "فضائي"
      },
      {
        "ref": "sticker:3d/robot",
        "label": "روبوت"
      },
      {
        "ref": "sticker:3d/pile-of-poo",
        "label": "مقرف"
      }
    ]
  },
  {
    "id": "love",
    "name": "حب وقلوب",
    "kind": "image",
    "items": [
      {
        "ref": "sticker:3d/red-heart",
        "label": "قلب أحمر"
      },
      {
        "ref": "sticker:3d/orange-heart",
        "label": "قلب برتقالي"
      },
      {
        "ref": "sticker:3d/yellow-heart",
        "label": "قلب أصفر"
      },
      {
        "ref": "sticker:3d/green-heart",
        "label": "قلب أخضر"
      },
      {
        "ref": "sticker:3d/blue-heart",
        "label": "قلب أزرق"
      },
      {
        "ref": "sticker:3d/purple-heart",
        "label": "قلب بنفسجي"
      },
      {
        "ref": "sticker:3d/black-heart",
        "label": "قلب أسود"
      },
      {
        "ref": "sticker:3d/white-heart",
        "label": "قلب أبيض"
      },
      {
        "ref": "sticker:3d/pink-heart",
        "label": "قلب وردي"
      },
      {
        "ref": "sticker:3d/light-blue-heart",
        "label": "قلب سماوي"
      },
      {
        "ref": "sticker:3d/sparkling-heart",
        "label": "قلب لامع"
      },
      {
        "ref": "sticker:3d/growing-heart",
        "label": "حب يكبر"
      },
      {
        "ref": "sticker:3d/beating-heart",
        "label": "قلب ينبض"
      },
      {
        "ref": "sticker:3d/two-hearts",
        "label": "قلبان"
      },
      {
        "ref": "sticker:3d/revolving-hearts",
        "label": "قلوب"
      },
      {
        "ref": "sticker:3d/heart-with-arrow",
        "label": "سهم الحب"
      },
      {
        "ref": "sticker:3d/heart-with-ribbon",
        "label": "هدية حب"
      },
      {
        "ref": "sticker:3d/heart-exclamation",
        "label": "حب كبير"
      },
      {
        "ref": "sticker:3d/broken-heart",
        "label": "قلب مكسور"
      },
      {
        "ref": "sticker:3d/mending-heart",
        "label": "قلب يتعافى"
      },
      {
        "ref": "sticker:3d/heart-on-fire",
        "label": "قلب مشتعل"
      },
      {
        "ref": "sticker:3d/love-letter",
        "label": "رسالة حب"
      },
      {
        "ref": "sticker:3d/heart-hands",
        "label": "قلب باليدين"
      },
      {
        "ref": "sticker:3d/kiss-mark",
        "label": "بوسة"
      },
      {
        "ref": "sticker:3d/rose",
        "label": "وردة"
      },
      {
        "ref": "sticker:3d/bouquet",
        "label": "باقة ورد"
      }
    ]
  },
  {
    "id": "hands",
    "name": "إيماءات",
    "kind": "image",
    "items": [
      {
        "ref": "sticker:3d/thumbs-up",
        "label": "تمام"
      },
      {
        "ref": "sticker:3d/thumbs-down",
        "label": "لا"
      },
      {
        "ref": "sticker:3d/clapping-hands",
        "label": "تصفيق"
      },
      {
        "ref": "sticker:3d/raising-hands",
        "label": "هييه"
      },
      {
        "ref": "sticker:3d/folded-hands",
        "label": "شكرًا"
      },
      {
        "ref": "sticker:3d/handshake",
        "label": "اتفاق"
      },
      {
        "ref": "sticker:3d/waving-hand",
        "label": "سلام"
      },
      {
        "ref": "sticker:3d/ok-hand",
        "label": "أوكي"
      },
      {
        "ref": "sticker:3d/victory-hand",
        "label": "نصر"
      },
      {
        "ref": "sticker:3d/crossed-fingers",
        "label": "بالتوفيق"
      },
      {
        "ref": "sticker:3d/love-you-gesture",
        "label": "أحبك"
      },
      {
        "ref": "sticker:3d/sign-of-the-horns",
        "label": "روك"
      },
      {
        "ref": "sticker:3d/call-me-hand",
        "label": "كلمني"
      },
      {
        "ref": "sticker:3d/flexed-biceps",
        "label": "قوة"
      },
      {
        "ref": "sticker:3d/writing-hand",
        "label": "يكتب"
      },
      {
        "ref": "sticker:3d/raised-fist",
        "label": "قبضة"
      },
      {
        "ref": "sticker:3d/oncoming-fist",
        "label": "لكمة"
      },
      {
        "ref": "sticker:3d/open-hands",
        "label": "تفضل"
      },
      {
        "ref": "sticker:3d/palms-up-together",
        "label": "دعاء"
      },
      {
        "ref": "sticker:3d/pinched-fingers",
        "label": "يعني إيه"
      },
      {
        "ref": "sticker:3d/index-pointing-up",
        "label": "فكرة"
      },
      {
        "ref": "sticker:3d/backhand-index-pointing-right",
        "label": "هنا"
      },
      {
        "ref": "sticker:3d/raised-hand",
        "label": "سؤال"
      },
      {
        "ref": "sticker:3d/hand-with-fingers-splayed",
        "label": "استنى"
      },
      {
        "ref": "sticker:3d/nail-polish",
        "label": "رايق"
      },
      {
        "ref": "sticker:3d/eyes",
        "label": "عيون"
      },
      {
        "ref": "sticker:3d/brain",
        "label": "مخ"
      }
    ]
  },
  {
    "id": "study",
    "name": "دراسة وجامعة",
    "kind": "image",
    "items": [
      {
        "ref": "sticker:3d/books",
        "label": "كتب"
      },
      {
        "ref": "sticker:3d/open-book",
        "label": "كتاب مفتوح"
      },
      {
        "ref": "sticker:3d/notebook",
        "label": "دفتر"
      },
      {
        "ref": "sticker:3d/notebook-with-decorative-cover",
        "label": "كشكول"
      },
      {
        "ref": "sticker:3d/ledger",
        "label": "سجل"
      },
      {
        "ref": "sticker:3d/memo",
        "label": "ملاحظات"
      },
      {
        "ref": "sticker:3d/pencil",
        "label": "قلم رصاص"
      },
      {
        "ref": "sticker:3d/fountain-pen",
        "label": "قلم حبر"
      },
      {
        "ref": "sticker:3d/pen",
        "label": "قلم"
      },
      {
        "ref": "sticker:3d/crayon",
        "label": "تلوين"
      },
      {
        "ref": "sticker:3d/straight-ruler",
        "label": "مسطرة"
      },
      {
        "ref": "sticker:3d/triangular-ruler",
        "label": "مثلث"
      },
      {
        "ref": "sticker:3d/paperclip",
        "label": "مشبك"
      },
      {
        "ref": "sticker:3d/pushpin",
        "label": "دبوس"
      },
      {
        "ref": "sticker:3d/scissors",
        "label": "مقص"
      },
      {
        "ref": "sticker:3d/graduation-cap",
        "label": "تخرج"
      },
      {
        "ref": "sticker:3d/school",
        "label": "مدرسة"
      },
      {
        "ref": "sticker:3d/backpack",
        "label": "شنطة"
      },
      {
        "ref": "sticker:3d/laptop",
        "label": "لابتوب"
      },
      {
        "ref": "sticker:3d/desktop-computer",
        "label": "كمبيوتر"
      },
      {
        "ref": "sticker:3d/mobile-phone",
        "label": "موبايل"
      },
      {
        "ref": "sticker:3d/abacus",
        "label": "حساب"
      },
      {
        "ref": "sticker:3d/microscope",
        "label": "ميكروسكوب"
      },
      {
        "ref": "sticker:3d/telescope",
        "label": "تلسكوب"
      },
      {
        "ref": "sticker:3d/test-tube",
        "label": "أنبوب اختبار"
      },
      {
        "ref": "sticker:3d/dna",
        "label": "دي إن إيه"
      },
      {
        "ref": "sticker:3d/magnet",
        "label": "مغناطيس"
      },
      {
        "ref": "sticker:3d/light-bulb",
        "label": "فكرة"
      },
      {
        "ref": "sticker:3d/alarm-clock",
        "label": "منبه"
      },
      {
        "ref": "sticker:3d/hourglass-done",
        "label": "الوقت خلص"
      },
      {
        "ref": "sticker:3d/stopwatch",
        "label": "تايمر"
      },
      {
        "ref": "sticker:3d/calendar",
        "label": "تقويم"
      },
      {
        "ref": "sticker:3d/spiral-calendar",
        "label": "جدول"
      },
      {
        "ref": "sticker:3d/card-index-dividers",
        "label": "ملفات"
      },
      {
        "ref": "sticker:3d/open-file-folder",
        "label": "ملف"
      },
      {
        "ref": "sticker:3d/clipboard",
        "label": "لوحة"
      },
      {
        "ref": "sticker:3d/chart-increasing",
        "label": "تقدم"
      },
      {
        "ref": "sticker:3d/bar-chart",
        "label": "إحصاء"
      },
      {
        "ref": "sticker:3d/bookmark-tabs",
        "label": "فهرس"
      },
      {
        "ref": "sticker:3d/magnifying-glass-tilted-left",
        "label": "بحث"
      },
      {
        "ref": "sticker:3d/globe-showing-europe-africa",
        "label": "جغرافيا"
      },
      {
        "ref": "sticker:3d/teacher",
        "label": "دكتور"
      },
      {
        "ref": "sticker:3d/student",
        "label": "طالب"
      },
      {
        "ref": "sticker:3d/hot-beverage",
        "label": "قهوة المذاكرة"
      },
      {
        "ref": "sticker:3d/battery",
        "label": "طاقة"
      },
      {
        "ref": "sticker:3d/low-battery",
        "label": "فاصل"
      },
      {
        "ref": "sticker:3d/speech-balloon",
        "label": "كلام"
      },
      {
        "ref": "sticker:3d/thought-balloon",
        "label": "تفكير"
      },
      {
        "ref": "sticker:3d/check-mark-button",
        "label": "تم"
      },
      {
        "ref": "sticker:3d/cross-mark",
        "label": "خطأ"
      },
      {
        "ref": "sticker:3d/hundred-points",
        "label": "100"
      },
      {
        "ref": "sticker:3d/trophy",
        "label": "كأس"
      },
      {
        "ref": "sticker:3d/1st-place-medal",
        "label": "المركز الأول"
      },
      {
        "ref": "sticker:3d/sports-medal",
        "label": "ميدالية"
      }
    ]
  },
  {
    "id": "party",
    "name": "احتفال",
    "kind": "image",
    "items": [
      {
        "ref": "sticker:3d/party-popper",
        "label": "مبروك"
      },
      {
        "ref": "sticker:3d/confetti-ball",
        "label": "كونفيتي"
      },
      {
        "ref": "sticker:3d/balloon",
        "label": "بالون"
      },
      {
        "ref": "sticker:3d/wrapped-gift",
        "label": "هدية"
      },
      {
        "ref": "sticker:3d/birthday-cake",
        "label": "عيد ميلاد"
      },
      {
        "ref": "sticker:3d/shortcake",
        "label": "كيك"
      },
      {
        "ref": "sticker:3d/sparkles",
        "label": "بريق"
      },
      {
        "ref": "sticker:3d/fireworks",
        "label": "ألعاب نارية"
      },
      {
        "ref": "sticker:3d/sparkler",
        "label": "شمروخ"
      },
      {
        "ref": "sticker:3d/glowing-star",
        "label": "نجمة"
      },
      {
        "ref": "sticker:3d/star",
        "label": "نجم"
      },
      {
        "ref": "sticker:3d/crown",
        "label": "ملك"
      },
      {
        "ref": "sticker:3d/gem-stone",
        "label": "جوهرة"
      },
      {
        "ref": "sticker:3d/ribbon",
        "label": "شريطة"
      },
      {
        "ref": "sticker:3d/clinking-glasses",
        "label": "نخب"
      },
      {
        "ref": "sticker:3d/clinking-beer-mugs",
        "label": "في صحتك"
      },
      {
        "ref": "sticker:3d/crescent-moon",
        "label": "هلال"
      },
      {
        "ref": "sticker:3d/mosque",
        "label": "مسجد"
      },
      {
        "ref": "sticker:3d/kaaba",
        "label": "الكعبة"
      },
      {
        "ref": "sticker:3d/rainbow",
        "label": "قوس قزح"
      },
      {
        "ref": "sticker:3d/sun-with-face",
        "label": "شمس"
      },
      {
        "ref": "sticker:3d/rocket",
        "label": "انطلاق"
      },
      {
        "ref": "sticker:3d/bullseye",
        "label": "في الهدف"
      }
    ]
  },
  {
    "id": "animals",
    "name": "حيوانات",
    "kind": "image",
    "items": [
      {
        "ref": "sticker:3d/cat-face",
        "label": "قطة"
      },
      {
        "ref": "sticker:3d/grinning-cat",
        "label": "قطة سعيدة"
      },
      {
        "ref": "sticker:3d/cat-with-tears-of-joy",
        "label": "قطة تضحك"
      },
      {
        "ref": "sticker:3d/smiling-cat-with-heart-eyes",
        "label": "قطة معجبة"
      },
      {
        "ref": "sticker:3d/weary-cat",
        "label": "قطة تعبانة"
      },
      {
        "ref": "sticker:3d/crying-cat",
        "label": "قطة تبكي"
      },
      {
        "ref": "sticker:3d/pouting-cat",
        "label": "قطة زعلانة"
      },
      {
        "ref": "sticker:3d/dog-face",
        "label": "كلب"
      },
      {
        "ref": "sticker:3d/fox",
        "label": "ثعلب"
      },
      {
        "ref": "sticker:3d/bear",
        "label": "دب"
      },
      {
        "ref": "sticker:3d/panda",
        "label": "باندا"
      },
      {
        "ref": "sticker:3d/koala",
        "label": "كوالا"
      },
      {
        "ref": "sticker:3d/tiger-face",
        "label": "نمر"
      },
      {
        "ref": "sticker:3d/lion",
        "label": "أسد"
      },
      {
        "ref": "sticker:3d/cow-face",
        "label": "بقرة"
      },
      {
        "ref": "sticker:3d/pig-face",
        "label": "خنزير صغير"
      },
      {
        "ref": "sticker:3d/frog",
        "label": "ضفدع"
      },
      {
        "ref": "sticker:3d/monkey-face",
        "label": "قرد"
      },
      {
        "ref": "sticker:3d/see-no-evil-monkey",
        "label": "مش شايف"
      },
      {
        "ref": "sticker:3d/hear-no-evil-monkey",
        "label": "مش سامع"
      },
      {
        "ref": "sticker:3d/speak-no-evil-monkey",
        "label": "ساكت"
      },
      {
        "ref": "sticker:3d/chicken",
        "label": "دجاجة"
      },
      {
        "ref": "sticker:3d/baby-chick",
        "label": "كتكوت"
      },
      {
        "ref": "sticker:3d/penguin",
        "label": "بطريق"
      },
      {
        "ref": "sticker:3d/owl",
        "label": "بومة"
      },
      {
        "ref": "sticker:3d/eagle",
        "label": "نسر"
      },
      {
        "ref": "sticker:3d/unicorn",
        "label": "يونيكورن"
      },
      {
        "ref": "sticker:3d/horse-face",
        "label": "حصان"
      },
      {
        "ref": "sticker:3d/rabbit-face",
        "label": "أرنب"
      },
      {
        "ref": "sticker:3d/hamster",
        "label": "هامستر"
      },
      {
        "ref": "sticker:3d/sloth",
        "label": "كسلان"
      },
      {
        "ref": "sticker:3d/turtle",
        "label": "سلحفاة"
      },
      {
        "ref": "sticker:3d/snail",
        "label": "حلزون"
      },
      {
        "ref": "sticker:3d/butterfly",
        "label": "فراشة"
      },
      {
        "ref": "sticker:3d/honeybee",
        "label": "نحلة"
      },
      {
        "ref": "sticker:3d/lady-beetle",
        "label": "دعسوقة"
      },
      {
        "ref": "sticker:3d/dolphin",
        "label": "دولفين"
      },
      {
        "ref": "sticker:3d/whale",
        "label": "حوت"
      },
      {
        "ref": "sticker:3d/octopus",
        "label": "أخطبوط"
      },
      {
        "ref": "sticker:3d/camel",
        "label": "جمل"
      },
      {
        "ref": "sticker:3d/dragon-face",
        "label": "تنين"
      },
      {
        "ref": "sticker:3d/t-rex",
        "label": "ديناصور"
      }
    ]
  },
  {
    "id": "food",
    "name": "أكل وشرب",
    "kind": "image",
    "items": [
      {
        "ref": "sticker:3d/hot-beverage",
        "label": "شاي"
      },
      {
        "ref": "sticker:3d/teacup-without-handle",
        "label": "كوب شاي"
      },
      {
        "ref": "sticker:3d/bubble-tea",
        "label": "بابل تي"
      },
      {
        "ref": "sticker:3d/cup-with-straw",
        "label": "عصير"
      },
      {
        "ref": "sticker:3d/tropical-drink",
        "label": "كوكتيل"
      },
      {
        "ref": "sticker:3d/glass-of-milk",
        "label": "لبن"
      },
      {
        "ref": "sticker:3d/pizza",
        "label": "بيتزا"
      },
      {
        "ref": "sticker:3d/hamburger",
        "label": "برجر"
      },
      {
        "ref": "sticker:3d/french-fries",
        "label": "بطاطس"
      },
      {
        "ref": "sticker:3d/hot-dog",
        "label": "هوت دوج"
      },
      {
        "ref": "sticker:3d/stuffed-flatbread",
        "label": "شاورما"
      },
      {
        "ref": "sticker:3d/falafel",
        "label": "فلافل"
      },
      {
        "ref": "sticker:3d/taco",
        "label": "تاكو"
      },
      {
        "ref": "sticker:3d/burrito",
        "label": "بوريتو"
      },
      {
        "ref": "sticker:3d/spaghetti",
        "label": "مكرونة"
      },
      {
        "ref": "sticker:3d/steaming-bowl",
        "label": "شوربة"
      },
      {
        "ref": "sticker:3d/curry-rice",
        "label": "رز"
      },
      {
        "ref": "sticker:3d/cooked-rice",
        "label": "أرز"
      },
      {
        "ref": "sticker:3d/poultry-leg",
        "label": "فراخ"
      },
      {
        "ref": "sticker:3d/cheese-wedge",
        "label": "جبنة"
      },
      {
        "ref": "sticker:3d/bread",
        "label": "عيش"
      },
      {
        "ref": "sticker:3d/croissant",
        "label": "كرواسون"
      },
      {
        "ref": "sticker:3d/pancakes",
        "label": "بان كيك"
      },
      {
        "ref": "sticker:3d/waffle",
        "label": "وافل"
      },
      {
        "ref": "sticker:3d/doughnut",
        "label": "دونات"
      },
      {
        "ref": "sticker:3d/cookie",
        "label": "كوكيز"
      },
      {
        "ref": "sticker:3d/chocolate-bar",
        "label": "شوكولاتة"
      },
      {
        "ref": "sticker:3d/candy",
        "label": "حلوى"
      },
      {
        "ref": "sticker:3d/lollipop",
        "label": "مصاصة"
      },
      {
        "ref": "sticker:3d/ice-cream",
        "label": "آيس كريم"
      },
      {
        "ref": "sticker:3d/soft-ice-cream",
        "label": "كون"
      },
      {
        "ref": "sticker:3d/popcorn",
        "label": "فشار"
      },
      {
        "ref": "sticker:3d/watermelon",
        "label": "بطيخ"
      },
      {
        "ref": "sticker:3d/strawberry",
        "label": "فراولة"
      },
      {
        "ref": "sticker:3d/banana",
        "label": "موز"
      },
      {
        "ref": "sticker:3d/red-apple",
        "label": "تفاحة"
      },
      {
        "ref": "sticker:3d/avocado",
        "label": "أفوكادو"
      },
      {
        "ref": "sticker:3d/mango",
        "label": "مانجا"
      }
    ]
  },
  {
    "id": "vibes",
    "name": "رموز ومزاج",
    "kind": "image",
    "items": [
      {
        "ref": "sticker:3d/fire",
        "label": "نار"
      },
      {
        "ref": "sticker:3d/high-voltage",
        "label": "طاقة"
      },
      {
        "ref": "sticker:3d/collision",
        "label": "بوم"
      },
      {
        "ref": "sticker:3d/dizzy",
        "label": "دوخة"
      },
      {
        "ref": "sticker:3d/zzz",
        "label": "نوم"
      },
      {
        "ref": "sticker:3d/sweat-droplets",
        "label": "عرق"
      },
      {
        "ref": "sticker:3d/dashing-away",
        "label": "جري"
      },
      {
        "ref": "sticker:3d/speech-balloon",
        "label": "دردشة"
      },
      {
        "ref": "sticker:3d/right-anger-bubble",
        "label": "غضب"
      },
      {
        "ref": "sticker:3d/red-question-mark",
        "label": "سؤال"
      },
      {
        "ref": "sticker:3d/red-exclamation-mark",
        "label": "تنبيه"
      },
      {
        "ref": "sticker:3d/warning",
        "label": "تحذير"
      },
      {
        "ref": "sticker:3d/no-entry",
        "label": "ممنوع"
      },
      {
        "ref": "sticker:3d/prohibited",
        "label": "لا"
      },
      {
        "ref": "sticker:3d/stop-sign",
        "label": "قف"
      },
      {
        "ref": "sticker:3d/check-mark",
        "label": "صح"
      },
      {
        "ref": "sticker:3d/ballot-box-with-ballot",
        "label": "تصويت"
      },
      {
        "ref": "sticker:3d/bell",
        "label": "جرس"
      },
      {
        "ref": "sticker:3d/megaphone",
        "label": "إعلان"
      },
      {
        "ref": "sticker:3d/loudspeaker",
        "label": "مكبر صوت"
      },
      {
        "ref": "sticker:3d/musical-notes",
        "label": "موسيقى"
      },
      {
        "ref": "sticker:3d/headphone",
        "label": "سماعة"
      },
      {
        "ref": "sticker:3d/video-game",
        "label": "جيمنج"
      },
      {
        "ref": "sticker:3d/soccer-ball",
        "label": "كورة"
      },
      {
        "ref": "sticker:3d/basketball",
        "label": "سلة"
      },
      {
        "ref": "sticker:3d/camera-with-flash",
        "label": "تصوير"
      },
      {
        "ref": "sticker:3d/airplane",
        "label": "سفر"
      },
      {
        "ref": "sticker:3d/automobile",
        "label": "عربية"
      },
      {
        "ref": "sticker:3d/house",
        "label": "البيت"
      },
      {
        "ref": "sticker:3d/full-moon-face",
        "label": "قمر"
      },
      {
        "ref": "sticker:3d/snowflake",
        "label": "تلج"
      },
      {
        "ref": "sticker:3d/umbrella-with-rain-drops",
        "label": "مطر"
      },
      {
        "ref": "sticker:3d/money-bag",
        "label": "فلوس"
      }
    ]
  },
  {
    "id": "animated",
    "name": "متحركة",
    "kind": "image",
    "items": [
      {
        "ref": "sticker:anim/1f923",
        "label": "ميت من الضحك"
      },
      {
        "ref": "sticker:anim/1f602",
        "label": "ضحك"
      },
      {
        "ref": "sticker:anim/1f609",
        "label": "غمزة"
      },
      {
        "ref": "sticker:anim/1f60a",
        "label": "خجول"
      },
      {
        "ref": "sticker:anim/1f970",
        "label": "حب"
      },
      {
        "ref": "sticker:anim/1f60d",
        "label": "معجب"
      },
      {
        "ref": "sticker:anim/1f929",
        "label": "منبهر"
      },
      {
        "ref": "sticker:anim/1f618",
        "label": "قبلة"
      },
      {
        "ref": "sticker:anim/1f917",
        "label": "حضن"
      },
      {
        "ref": "sticker:anim/1f92d",
        "label": "أوبس"
      },
      {
        "ref": "sticker:anim/1f914",
        "label": "تفكير"
      },
      {
        "ref": "sticker:anim/1fae1",
        "label": "تحية"
      },
      {
        "ref": "sticker:anim/1f644",
        "label": "زهقان"
      },
      {
        "ref": "sticker:anim/1f60f",
        "label": "خبيث"
      },
      {
        "ref": "sticker:anim/1f62c",
        "label": "متوتر"
      },
      {
        "ref": "sticker:anim/1f634",
        "label": "نائم"
      },
      {
        "ref": "sticker:anim/1f92f",
        "label": "انفجار دماغ"
      },
      {
        "ref": "sticker:anim/1f973",
        "label": "حفلة"
      },
      {
        "ref": "sticker:anim/1f60e",
        "label": "كول"
      },
      {
        "ref": "sticker:anim/1f913",
        "label": "دحيح"
      },
      {
        "ref": "sticker:anim/1f97a",
        "label": "رجاء"
      },
      {
        "ref": "sticker:anim/1f979",
        "label": "كاتم دموعه"
      },
      {
        "ref": "sticker:anim/1f62d",
        "label": "منهار"
      },
      {
        "ref": "sticker:anim/1f631",
        "label": "رعب"
      },
      {
        "ref": "sticker:anim/1f971",
        "label": "تثاؤب"
      },
      {
        "ref": "sticker:anim/1f621",
        "label": "غاضب"
      },
      {
        "ref": "sticker:anim/1f480",
        "label": "مت"
      },
      {
        "ref": "sticker:anim/1f648",
        "label": "مش شايف"
      },
      {
        "ref": "sticker:anim/2764-fe0f",
        "label": "قلب"
      },
      {
        "ref": "sticker:anim/1f494",
        "label": "قلب مكسور"
      },
      {
        "ref": "sticker:anim/2764-fe0f-200d-1f525",
        "label": "قلب مشتعل"
      },
      {
        "ref": "sticker:anim/1f525",
        "label": "نار"
      },
      {
        "ref": "sticker:anim/2728",
        "label": "بريق"
      },
      {
        "ref": "sticker:anim/1f389",
        "label": "مبروك"
      },
      {
        "ref": "sticker:anim/1f382",
        "label": "عيد ميلاد"
      },
      {
        "ref": "sticker:anim/1f44d",
        "label": "تمام"
      },
      {
        "ref": "sticker:anim/1f44f",
        "label": "تصفيق"
      },
      {
        "ref": "sticker:anim/1f64f",
        "label": "شكرًا"
      },
      {
        "ref": "sticker:anim/1f44b",
        "label": "سلام"
      },
      {
        "ref": "sticker:anim/1f4aa",
        "label": "قوة"
      },
      {
        "ref": "sticker:anim/1f440",
        "label": "عيون"
      },
      {
        "ref": "sticker:anim/1f4af",
        "label": "100"
      }
    ]
  }
];
